{% set name = "skein" %}
{% set version = "0.8.0" %}
{% set pkg_loc = "py3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/{{ pkg_loc }}/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-{{ pkg_loc }}-none-any.whl
  sha256: 71da4a16e2bba4d99fa90454b58e951463452596a6e6afaaf024a0d1cce87d3f

build:
  number: 1
  skip: True  # [win or py<35]
  script: python -m pip install --no-deps --ignore-installed {{ name }}-{{ version }}-{{ pkg_loc }}-none-any.whl
  entry_points:
    - skein = skein.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cryptography
    - grpcio >=1.11.0
    - protobuf >=3.5.0
    - pyyaml

test:
  imports:
    - skein
    - skein.proto
    - skein.recipes
  commands:
    - skein --help

about:
  home: https://jcrist.github.io/skein/
  license: BSD-3-Clause
  license_family: BSD
  summary: A simple tool and library for deploying applications on Apache YARN
  doc_url: https://jcrist.github.io/skein/
  dev_url: https://github.com/jcrist/skein

extra:
  recipe-maintainers:
    - jcrist
