{% set name = "skein" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/py2.py3/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-py2.py3-none-any.whl
  sha256: d4b0acd779ac1ca638d562c88bcc9764a40e390a927ed89fb178e3aeb64fc47a

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed {{ name }}-{{ version }}-py2.py3-none-any.whl
  entry_points:
    - skein = skein.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cryptography
    - grpcio >=1.11.0
    - protobuf >=3.5.0
    - pyyaml

test:
  imports:
    - skein
    - skein.proto
  commands:
    - skein --help

about:
  home: https://jcrist.github.io/skein/
  license: BSD-3-Clause
  license_family: BSD
  summary: A simple tool and library for deploying applications on Apache YARN
  doc_url: https://jcrist.github.io/skein/
  dev_url: https://github.com/jcrist/skein

extra:
  recipe-maintainers:
    - jcrist
